[package]
name = "training_task"
version = "0.1.0"
edition = "2021"
autors = ["Yaroslav Smirnov <d3156@mail.ru>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
